### ISSUE TITLE
Cannot set deactivatedMessage property on user model

### ISSUE THREAD

**Issue by CMaylone** [smartdevicelink/sdl_shaid#1]
**Preconditions**

* Logged in as Admin role

**Steps to recreate**

1. Send request to ```PUT /api/1/users/:userId```
  
  Body:
  ```
  {
    "activated": false,
    "deactivatedMessage": "Please set me"
  }
  ```

2. Response's ```deactivatedMessage``` message value is not set.

**Comment by ssmereka** [comment]
Server side is fixed.  However client side is not working as expected.
