### ISSUE TITLE
Add content to Help page

### ISSUE THREAD

**Issue by CMaylone** [smartdevicelink/sdl_shaid#32]

**Comment by ssmereka** [comment]
I think adding wiki-like help pages would be useful here.  So for example, there would be a page describing how to add an application, what each field is with examples, and what/when information is public/private.

What do you think?

**Comment by CMaylone** [comment]
As we discussed, I think we should focus on the more complex fields and actions. Things like OAuth tokens and revoking Application IDs.

**Comment by ssmereka** [comment]
TODO:  Update and proof read and Help docs with all changes for 1.0

**Comment by CMaylone** [comment]
User interface is going to be removed.
