### ISSUE TITLE
Creating duplicate user's results in cryptic user error message.

### ISSUE THREAD

**Issue by ssmereka** [smartdevicelink/sdl_shaid#4]
The duplicate key error message from Mongo DB is returned to the user if they try to register a username that already exists.

**Comment by ssmereka** [comment]
Added server side username validation.

**Comment by CMaylone** [comment]
@ssmereka Username validation is case sensitive. The existing username ```admin``` is invalid while ```Admin``` is valid.

**Comment by CMaylone** [comment]
Add client logic for this in a8a141d037173f4629f27ce2fb66faee5fbd6c2f. Forgot to tag the issue in commit message.
