### ISSUE TITLE
Password reset is currently not working.

### ISSUE THREAD

**Issue by ssmereka** [smartdevicelink/sdl_shaid#40]
**Steps:**
1. Performed a password reset request.
2. Received email and followed link.
3. Entered invalid security answer.
4. Entered new password.
5. Click submit button.
6. Nothing happened, no notification or anything.  Not sure what happened.
7. Entered correct security answer and click submit again.
8. Nothing happened, no notification or anything.  Not sure what happened.

**Comment by CMaylone** [comment]
@ssmereka I keep getting a 400: Invalid security answer whenever I hit this endpoint. The frontend should work correctly now.

**Comment by ssmereka** [comment]
This appears to be working on https://shaid.smartdevicelink.org are you still getting 400 errors?
