### ISSUE TITLE
Updating application's name clears all SDL servers.

### ISSUE THREAD

**Issue by ssmereka** [smartdevicelink/sdl_shaid#74]
When i update an existing application's using the front-end makes a post with an empty list of SDL servers, even though all the SDL servers were previously associated (checked).

```
{ name: 'appsss',
  description: 'app',
  applicationId: 'df7ea28c-d3df-4547-9cc5-0b5ebe163bc3',
  ios: { itunesUrl: 'http://app.com', urlScheme: 'app://' },
  android: { packageName: 'com.app.app', playStoreUrl: 'http://app.com' },
  sdlServers: [],
  deleted: false }
```

**Comment by CMaylone** [comment]
Confirmed, this affects other SDL and Application associations for Users as well.
