### ISSUE TITLE
Travis CI build 'randomly' fails

### ISSUE THREAD

**Issue by CMaylone** [smartdevicelink/sdl_shaid#8]
Travis CI build fails for a bunch of random reasons. 

**Example:** 
This [failing build 192](https://travis-ci.org/smartdevicelink/sdl_shaid/builds/60587343) did not modify anything that would cause that particular unit test to fail and the [previous successful build 191](https://travis-ci.org/smartdevicelink/sdl_shaid/builds/60559765) is fine. On top of that, sometimes you can just rerun the build and it will pass.

Perhaps there is a race condition?

**Comment by ssmereka** [comment]
I may have just pushed a fix for this.  Update here if you see it again.

**Comment by CMaylone** [comment]
[Build 202 Failed](https://travis-ci.org/smartdevicelink/sdl_shaid/builds/60758975). I did not make changes to the APIs.

**Comment by CMaylone** [comment]
Changed footer sizing and the API unit tests failed for [build](https://travis-ci.org/smartdevicelink/sdl_shaid/builds/60876740)

**Comment by ssmereka** [comment]
Got a decent hit with some luck and some logs.  Added more logs in a new commit to trace further.

**Error:**
```
cannot be individually queried
[SHAID_TEST Trace]: SdlServer.checkReadPermission(): Permission denied, invalid user role value of undefined
[SHAID_TEST Trace]: SdlServer.checkReadPermission(): Permission denied, invalid user role value of undefined
[SHAID_TEST Trace]: SdlServer.checkReadPermission(): Permission denied, invalid user role value of undefined
  1) by an OEM if not attached to their account and private, deactivated, or deleted.
```

**Comment by ssmereka** [comment]
Looks like the user attribute ```roles``` is empty when it should contain at least 1 role.  Not sure where the root of this problem is, but adding logs around the update method to see if we can track it down.

[Build 219 Error:](https://travis-ci.org/smartdevicelink/sdl_shaid/builds/61340112)
```
[SHAID_TEST Trace]: BearerStrategy(): User 000000000000000000000002 does not have any roles: []
...
[SHAID_TEST Trace]: User.checkWritePermission(): Permission Denied, user role is invalid undefined
  1) unknown resources.
...
 1) Users cannot request unknown resources.:
     Error: expected 400 "Bad Request", got 403 "Forbidden"
      at net.js:1277:10
```

**Comment by CMaylone** [comment]
Resolved by refactoring control flow when the app was started.

**Comment by CMaylone** [comment]
It happened again https://travis-ci.org/smartdevicelink/sdl_shaid/jobs/111320052
